run:
	gcc -o gabinete_exer05_t5l gabinete_exer05_t5l.c -lm
	./gabinete_exer05_t5l
	
noprint:
	gcc -o gabinete_exer05_t5l_noprint gabinete_exer05_t5l_noprint.c -lm
	./gabinete_exer05_t5l_noprint

2:
	gcc -o gabinete_exer02_t5l gabinete_exer02_t5l.c -lpthread -lm 
	./gabinete_exer02_t5l
	
