

run:
	gcc -o gabinete_exer01_t5l gabinete_exer01_t5l.c -lm
	./gabinete_exer01_t5l
	
noprint:
	gcc -o gabinete_exer01_t5l_noprint gabinete_exer01_t5l_noprint.c -lm
	./gabinete_exer01_t5l_noprint
	
1:
	gcc -o gabinete_exer01_t5l_2d gabinete_exer01_t5l_2d.c -lm
	./gabinete_exer01_t5l_2d